apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft 
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: openhack/minecraft-server:1.0
        ports:
        - containerPort: 25565
          name: game
        - containerPort: 25575
          name: console
        env:
        - name: EULA
          value: "TRUE"
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  type: LoadBalancer
  ports:
  - port: 25565
    name: game
    targetPort: game
  - port: 25575
    name: console
    targetPort: console
  selector:
    app: minecraft
