apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
      - name: minecraft-server
        image: openhack/minecraft-server:1.0
        ports:
        - containerPort: 25565
          name: game-server
        - containerPort: 25575
          name: console
        env:
        - name: EULA
          value: "TRUE"
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
spec:
  type: LoadBalancer
  ports:
  - port: 25565
    name: game-server
    targetPort: game-server
  - port: 25575
    name: console
    targetPort: console
  selector:
    app: minecraft-server
