apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-03-22T13:41:07Z
  labels:
    run: minecraft
  name: minecraft
  namespace: default
  resourceVersion: "14226"
  selfLink: /api/v1/namespaces/default/services/minecraft
  uid: ac5254bf-2dd6-11e8-96a2-0a58ac1f022f
spec:
  clusterIP: 10.0.184.224
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30062
    port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    run: minecraft
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 13.82.53.165
